version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: master
  ignore:
  - dependency-name: rollup
    versions:
    - 2.38.1
    - 2.38.2
    - 2.38.3
    - 2.38.4
    - 2.38.5
    - 2.39.0
  - dependency-name: svelte
    versions:
    - 3.32.0
    - 3.32.1
    - 3.32.2
  - dependency-name: postcss
    versions:
    - 8.2.4
    - 8.2.5
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
  - dependency-name: "@rollup/plugin-node-resolve"
    versions:
    - 11.1.1
  - dependency-name: autoprefixer
    versions:
    - 10.2.3
  - dependency-name: sirv-cli
    versions:
    - 1.0.10
